### ISSUE TITLE
about brass subset

### ISSUE THREAD

**Issue by 18443148644** [potsawee/podcast_trec2020#1]
Hello, excuse me. I want to know how to get the brass set of the podcast dataset you use, or where to download it? 
Thank you very much.

**Comment by potsawee** [comment]
For those who might still have this issue, I downloaded the brass set from Spotify. The Spotify Challenge 2020 organizers shared to data with us (if I remember correctly) via the Slack channel. See https://podcastsdataset.byspotify.com/

This is a copy of the brass set that I downloaded from Spotify: https://drive.google.com/file/d/13RTsjwsOhftG-ZS1j8WdFXnDbfSOBGl9/view?usp=sharing. The file simply contains the IDs of episodes after filtering.

Please note that I'm not the owner of this file, and it belongs to Spotify.
